ibelick/zola

app/components/chat/chat.tsx
cf https://github.com/ibelick/zola/issues/16
=> feat: add optimistic UI updates

app/components/chat/chat.tsx, app/components/history/history.tsx, app/components/layout/header.tsx, app/components/layout/user-menu.tsx
cf: https://github.com/ibelick/zola/issues/14
=> feat: implement lazy loading

INSTALL.md, app/types/database.types.ts, lib/api.ts
Add `last_active_at` in `user` table and in `incrementUsage`
=> feat: add last_active_at

app/components/header-go-back.tsx, app/components/history/command-history.tsx, app/components/history/drawer-history.tsx, app/components/layout/button-new-chat.tsx, app/components/layout/header.tsx, package.json
add prefetch on link to `/c/[id]` and `/`. Mostly in `history`
note: we will add pagination / infinite scroll later
=> feat: add prefetch

app/auth/callback/route.ts, app/components/header-go-back.tsx, app/components/history/command-history.tsx, app/components/history/drawer-history.tsx, app/components/layout/button-new-chat.tsx, app/components/layout/header.tsx, app/page.tsx, lib/chat-store/persist.ts, package.json
- add prefetch on link to /c/[id] and /. Mostly in history (
- add force-dynamic in home
- improve persist.ts
note: we will add pagination / infinite scroll later
=> feat: improve chat performance

app/c/[chatId]/page.tsx, app/components/chat/chat.tsx, app/components/history/command-history.tsx, app/components/history/drawer-history.tsx, app/components/history/history-trigger.tsx, app/components/history/utils.ts, app/layout.tsx, app/providers/chat-session-provider.tsx, lib/chat-store/messages/provider.tsx, package-lock.json, package.json
Improve the chat history user interface in the `CommandHistory` and `DrawerHistory` components. 
**Key updates include:**
- Chat Grouping: chats are now organized by time periods (Today, Last 7 Days, Last 30 Days, This Year, and Older) with clear headings.
- User-Friendly Date Formatting: added a function to display chat dates in a more understandable way, such as "Just now," "X minutes ago," or "March 25."
- Component Refactoring: created reusable components for editing, deleting, and displaying chat items to streamline the code.
- Performance Optimization: used hooks to improve performance and reduce unnecessary re-renders.
- Add ChatSessionProvider to manage the current chat: improve chat management (deletion / navigation)
=> feat: Improve chat history UI

app/components/chat-input/suggestions.tsx, app/components/history/command-history.tsx, app/components/history/history-trigger.tsx
- improve CommandHistory, use CommandItem on each row to do not lost focus
- add motion.create
=> feat: various updates

components/common/model-selector.tsx, lib/config.ts, package-lock.json, package.json
https://openai.com/index/gpt-4-1/
=> feat: add gpt-4.1

app/components/layout/user-menu.tsx
=> fix: truncate user email in user menu

app/agents/[agentSlug]/[chatId]/article.tsx, app/agents/[agentSlug]/[chatId]/header.tsx, app/agents/[agentSlug]/[chatId]/page.tsx, components/prompt-kit/message.tsx
- add shared agent chat screen
=> feat: add shared chat screen

INSTALL.md, supabase/seed.sql
- update schema in install.md
- add seed.sql in install.md
- update seed.sql
=> docs: update seed + install.md

lib/agent-store/load-github-agent.ts, lib/config.ts, supabase/seed.sql
- update zola-chat to zola repo
- fetch github desc when creating agent
=> feat: update github agent

lib/agent-store/load-github-agent.ts
- check if repo exist when we load github agent in chat
=> feat: add check if repo exist in loadGitHubAgent

app/components/agents/agent-card.tsx, app/components/chat/conversation.tsx, app/components/chat/link-markdown.tsx, app/components/chat/message-assistant.tsx, app/components/chat/tool-invocation.tsx, components/prompt-kit/loader.tsx, package-lock.json, package.json
- update ai package
- upate tool-invocation UI (loader, group tools, clean code)
=> feat: update tool-invocation UI

app/components/agents/dialog-agent.tsx, app/components/chat-input/select-model.tsx, app/components/layout/settings/settings-content.tsx, components/common/model-selector.tsx, components/common/model-selector/base.tsx, components/common/model-selector/pro-dialog.tsx, components/common/model-selector/sub-menu.tsx, components/prompt-kit/prompt-input.tsx, lib/config.ts
Improve model selector UI and add Pro dialog
=> feat: update model selector

.env.example, components/common/model-selector/base.tsx, components/icons/xai.tsx, lib/config.ts, lib/openproviders/env.ts, lib/openproviders/index.ts, lib/openproviders/provider-map.ts, lib/openproviders/types.ts, package-lock.json, package.json
- add xai provider
- add grok models
- add search model selector
=> feat: add grok, add search model selector

INSTALL.md, supabase/seed.sql
- rollback docker 
- update seed mcp
- add storage setup
=> docs: update install guide

app/components/history/command-history.tsx, app/components/layout/button-new-chat.tsx, components/common/model-selector/base.tsx, components/common/model-selector/pro-dialog.tsx, components/common/model-selector/sub-menu.tsx, components/ui/command.tsx, components/ui/dialog.tsx
- Improve history UI and keyboard shortcuts 
- updated dialog styles
- updated command history layout
- added new shortcuts: new chat, switch model, history
=> feat: improve history UI, add keyboard shortcuts

app/components/chat-input/chat-input.tsx, app/components/layout/agent-link.tsx, app/components/layout/button-new-chat.tsx, components/common/model-selector/base.tsx
- missing aria-labels
- radius top model selector
- non-auth input pasting
=> fix: various small UI fixes

app/components/chat/conversation.tsx, app/components/chat/message-assistant.tsx, app/components/chat/message-user.tsx, app/components/chat/message.tsx, app/layout.tsx, components/common/model-selector/base.tsx, components/ui/tooltip.tsx
- update tooltip, move tooltip provider
- update buttons message action UI
- fix search dark mode input model selector 
- don't show actions for the last message while streaming
=> feat: update message action, update tooltip

app/components/chat/conversation.tsx, lib/config.ts
- switch to gpt-4.1-nano as default model
=> feat: switch default model

app/components/chat-input/chat-input.tsx
- add message in chat input if agent doesn't support tool
=> feat: add message if agent doesn't support tool

app/components/layout/sidebar/app-sidebar.tsx
- update sidebar history trigger animation
=> fix: sidebar history trigger animation

app/components/chat-input/chat-input.tsx, app/components/chat/chat.tsx, app/components/chat/use-chat-handlers.ts, app/components/layout/settings/settings-content.tsx, app/components/layout/settings/system-prompt-section.tsx, app/components/suggestions/prompt-system.tsx, app/types/database.types.ts, lib/agents/load-agent.ts
- Added UI for editing the system prompt
- Introduced system_prompt column in the user schema
- Added backend logic to save and load user system prompt
- Removed legacy agent mode logic
- Fixed: prevent agent.tools from being null when empty
=> feat: add global system prompt user

app/components/chat/tool-invocation.tsx, components/prompt-kit/code-block.tsx
- update dark mode colors for tool UI and code block
=> fix: dark mode tool ui, code block

app/components/layout/header.tsx
- fix command history duplication with sidebar
=> fix: command history duplication

app/components/chat-input/chat-input.tsx, app/globals.css, components/common/model-selector/base.tsx, components/prompt-kit/code-block.tsx
=> feat: update dark border input

lib/openproviders/provider-map.ts
Simple fix to make o1 a string key along with the others
=> Added missing quotes to o1 in provider-map.ts

app/components/chat-input/chat-input.tsx, app/components/chat-input/file-list.tsx, app/components/chat-input/selected-agent.tsx, components/prompt-kit/prompt-input.tsx
- update chat input UI (mostly padding)
=> feat: update chat input UI

app/components/chat/use-chat-utils.ts
- fix typo on non pro remaining queries toast
=> fix: remaining query threshold typo

app/components/chat-input/chat-input.tsx, app/components/chat-input/suggestions.tsx, app/components/chat/chat.tsx, app/components/chat/use-chat-handlers.ts
- move useChatDraft in useChatUtils
- fix prompt suggestions animation
=> fix: chat suggestions animation

app/auth/error/page.tsx, app/auth/login-page.tsx, app/auth/page.tsx, app/components/chat-input/chat-input.tsx, app/components/chat-input/use-agent-command.ts, app/components/chat/chat.tsx, app/not-found.tsx, lib/agent-store/provider.tsx, package-lock.json, package.json
- wrap all useSearchParams 
- update to next": "^15.4.0-canary.47"
=> fix: useSearchParams with Suspense, update next

app/auth/login-page.tsx, app/components/chat-input/popover-content-auth.tsx, app/components/chat/dialog-auth.tsx, app/components/chat/link-markdown.tsx, app/components/layout/header.tsx, app/components/layout/settings/connections-section.tsx, app/components/layout/settings/provider-settings-section.tsx, components/common/model-selector/base.tsx, components/settings/settings-dialog.tsx
- fix img favicon
- dev only provider settings
- fix remove non auth agent link
- non button select model if loading
=> refactor: dev only settings models

app/components/history/chat-preview-panel.tsx, app/components/history/command-history.tsx, lib/hooks/use-chat-preview.tsx
=> feat: update history dialog

app/api/models/route.ts, app/api/user-key-status/route.ts, app/api/user-keys/route.ts, app/components/layout/settings/apikeys/byok-section.tsx, lib/model-store/provider.tsx, lib/models/index.ts
- add delete api key support
- add openai provider
=> feat: add delete api keys, add openai provider

.github/workflows/ci-cd.yml
Removed the GitHub Actions workflow trigger for pull_request to avoid running lint and test jobs on every PR.
=> feat: remove CI check on pull requests

app/components/chat/chat.tsx, app/components/layout/button-new-chat.tsx, app/components/layout/sidebar/app-sidebar.tsx, lib/chat-store/chats/provider.tsx
Improve chat creation flow
- fix redirect on first message
- update optimistic createNewChat
- reset message input when navigating to /
https://github.com/ibelick/zola/issues/204
=> fix: chat UX and message handling

app/components/chat/chat.tsx, app/components/chat/use-chat-core.ts, app/components/chat/use-chat-operations.ts, app/p/[projectId]/project-view.tsx
- add input to ensureChatExists
=> fix: add input title to newChat

app/components/chat/link-markdown.tsx, app/components/chat/multi-conversation.tsx, components/prompt-kit/code-block.tsx, middleware.ts, next.config.ts
- img link-mardkwon
- multi-chat max-w
- code block production
=> fix: various fixes
